### ISSUE TITLE
Error when restart a simulation in interactive mode

### ISSUE THREAD

**Issue by PennyQ** [maxwelltsai/SiMon#25]
The error is as below

> Please choose an action to continue: r
> ERROR [SEVERE]: unable to proceed the simulation /Users/penny/Works/simon_project/nbody6/Ncode/run/run_1k

and this is the status

> /Users/penny/Works/simon_project/nbody6/Ncode/run/run_1k
> /Users/penny/Works/simon_project/nbody6/Ncode/run/run_2k
> 0|---'root' 1969-12-31 19:00:00 1969-12-31 19:00:00
>     2|---'run_2k'   2016-09-26 17:20:12 2016-09-26 17:20:48
>     DONE    T=[0-80]        CID=-1  level=1
>     T=[0-0]     CID=2   level=0
> 1|-------'run_1k'   2016-10-22 22:19:22 2016-10-22 22:20:00
>         DONE    T=[0-80]        CID=-1  level=1
> 2|-------'run_2k'   2016-09-26 17:20:12 2016-09-26 17:20:48
>         DONE    T=[0-80]        CID=-1  level=1

@maxwelltsai Do you know how to do with it? Thanks!

**Comment by maxwelltsai** [comment]
The bug is fixed in some recent bug fixes. Closing the issue.
