### ISSUE TITLE
Fix the repeated info showing on interactive mode

### ISSUE THREAD

**Issue by PennyQ** [maxwelltsai/SiMon#30]
as below:
> 0|---'root'	1969-12-31 19:00:00	1969-12-31 19:00:00
    3|---'run_2k'	2016-09-26 17:20:12	2016-09-26 17:20:48
    DONE	T=[0-80]		CID=-1	level=1
	T=[0-0]		CID=3	level=0

the 3| should not be shown on root here

**Comment by maxwelltsai** [comment]
Fixed in #32
