### ISSUE TITLE
A logic conflict for start and stop

### ISSUE THREAD

**Issue by PennyQ** [maxwelltsai/SiMon#53]
I guess there are some trigger between start and stop, which requires these two actions to be done in sequence without interruption.

e.g. if users did `python simon.py start`, and at this time they update the simulation dir and did `python simon.py start` again, the simulations are actually not started, there is a need to do `python simon.py stop` first and then start again.

@maxwelltsai Any idea?

**Comment by PennyQ** [comment]
A simple idea is: give users a warning saying:
there is a daemon running, please stop the old one first using `python simon.py stop`, and start the new one again'

**Comment by PennyQ** [comment]
@maxwelltsai Can you show me how to find current Simon status (start or stop) in the log file? I think such a status-check should be added to `daemon_mode` function in `simon.py`, please advise me if I am wrong, thanks!

**Comment by maxwelltsai** [comment]
@PennyQ The easiest way to detect the current SiMon status is to check the existence of the daemon log file:

`if os.path.isfile(os.path.join(__simon_dir__, 'SiMon_daemon.pid'):
    # daemon running
else:
    # daemon not running`
