### ISSUE TITLE
Wrong usage msg pop up in simon-start/stop/interactive command line

### ISSUE THREAD

**Issue by PennyQ** [maxwelltsai/SiMon#61]
@maxwelltsai There is a 'usage' msg pop out (as below) when using `simon-start` command line, while the command line is correct and Simon daemon is already running. Do you know where in the code does this happen? I didn't found `print_help` function got called in this case. Thanks!

➜  SiMon git:(logic_conflict_start_stop) ✗ simon-start
usage: simon-start start|stop|restart

**Comment by maxwelltsai** [comment]
@PennyQ It is here: https://github.com/maxwelltsai/SiMon/blob/master/SiMon/simon.py#L505

If the command line argument is not `start`, `stop`, or `interactive`, then it will show the help.

**Comment by PennyQ** [comment]
solved in #62
