### ISSUE TITLE
Simulation status is always shown as 'DONE'

### ISSUE THREAD

**Issue by PennyQ** [maxwelltsai/SiMon#9]
As seen below, as the running time is changed, the status is not changed as still 'DONE'
@maxwelltsai is this normal? 

> 0|---'root'   1969-12-31 19:00:00 1969-12-31 19:00:00
>     DONE    T=[0-0]     CID=1   level=0
> 1|-------'run_1k'   2016-09-26 17:20:12 2016-09-26 17:20:25
>         DONE    T=[0-40]    unknown CID=-1  level=1
> 2|-------'run_2k'   2016-09-26 17:20:12 2016-09-26 17:20:25
>         DONE    T=[0-40]    unknown CID=-1  level=1

and 

> 0|---'root'   1969-12-31 19:00:00 1969-12-31 19:00:00
>     DONE    T=[0-0]     CID=1   level=0
> 1|-------'run_1k'   2016-09-26 17:20:12 2016-09-26 17:20:44
>         DONE    T=[0-60]    unknown CID=-1  level=1
> 2|-------'run_2k'   2016-09-26 17:20:12 2016-09-26 17:20:44
>         DONE    T=[0-60]    unknown CID=-1  level=1

**Comment by maxwelltsai** [comment]
@PennyQ No this is abnormal. We have to fix it.

**Comment by PennyQ** [comment]
@maxwelltsai Do you want to work on it? you could assign to yourself on the right panel ;)

**Comment by maxwelltsai** [comment]
@PennyQ Sure I can do that.

**Comment by maxwelltsai** [comment]
Fixed in #35
